apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: secure-ticketing
  labels:
    app.kubernetes.io/name: secure-event-ticketing
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: secure-event-ticketing
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: 3000
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: secure-ticketing
  labels:
    app.kubernetes.io/name: secure-event-ticketing
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: secure-event-ticketing
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 8080
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: secure-ticketing
  labels:
    app.kubernetes.io/name: secure-event-ticketing
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: secure-event-ticketing
    app.kubernetes.io/component: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: secure-ticketing
  labels:
    app.kubernetes.io/name: secure-event-ticketing
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: secure-event-ticketing
    app.kubernetes.io/component: redis
  ports:
    - name: redis
      port: 6379
      targetPort: redis
