apiVersion: v1
kind: ServiceAccount
metadata:
  name: ticketing-app
  namespace: secure-ticketing
  labels:
    app.kubernetes.io/name: secure-event-ticketing
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ticketing-data
  namespace: secure-ticketing
  labels:
    app.kubernetes.io/name: secure-event-ticketing
automountServiceAccountToken: false
